name: flutter_oxygen
description: "这是oxygen组专用的一个公共包"
version: 0.0.1
homepage: https://github.com/sj-distributor/flutter_oxygen

environment:
  sdk: ">=3.8.0 < 4.0.0"
  flutter: ">=3.32.5"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^16.1.0
  json_annotation: ^4.9.0
  recase: ^4.1.0
  yaml_edit: ^2.2.1
  yaml: ^3.1.2
  xml: ^6.5.0
  mustache_template: ^2.0.0
  build_runner: ^2.4.15
  dio: ^5.9.0
  riverpod: ^3.0.0
  flutter_riverpod: ^3.0.0
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  flutter_smart_dialog: ^4.9.8+9
  device_info_plus: ^12.1.0
  get_user_agent: ^1.1.0
  meta_seo: ^3.0.9
  window_manager: ^0.5.1
  copy_with_extension: ^9.1.0
  copy_with_extension_gen: ^9.1.0
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.9.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
